### ISSUE TITLE
Allow some custom options (bwlimit, -a, etc...)

### ISSUE THREAD

**Issue by mysterfr** [lfreist/rsyncer#5]
Hi, 

Nice work ! would it be possible to add another parameter such as `options` which would allow the use to pass extra rsync options ?
For instance, I would like to be able to pass options such as:

```
--bwlimit=50000
-t
--no-dirs 
--no-R 
etc.
```

or any needed rsync option for that matter...
A bit like what's been done here : https://github.com/gchamon/sysrsync ?

**Comment by lfreist** [comment]
Hi @mysterfr,
It is possible to add additional rsync options that are not explicitly named as arguments in the functions.
You can just add them as keyword arguments (kwargs) as follows:

```
from rsyncer.rsync import Syncer, rsync

with Syncer("/source/dir", "/dest/dir", bwlimit=50000, t=None, no_dir=None, no_R=None) as s:
    s.run()

#or

rsync("/source/dir", "/dest/dir", bwlimit=50000, t=None, no_dir=None, no_R=None)
```
will run rsync as the equivalent shell command: `rsync /source/dir /dest/dir --bwlimit 50000 -t --no-dir` would.

You can add whatever option. rsyncer will not check, if it is an actual rsync command.


Is this what you're looking for?

**Comment by mysterfr** [comment]
Hi, yes that's perfect, thanks for the quick reply !
